# Generated by Django 6.0 on 2025-12-18 21:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Category name (e.g., "Trees", "Retreats")',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the name",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Category description for SEO and display"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Material Symbol icon name", max_length=50
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Category banner/thumbnail image URL"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is visible in the catalog",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which to display categories"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Product title", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the title",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full product description (supports markdown)"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Brief description for cards and SEO meta",
                        max_length=300,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("Retreat", "Retreat"),
                            ("Tree", "Tree"),
                            ("PhysicalProduct", "Physical Product"),
                            ("DigitalGoods", "Digital Goods"),
                        ],
                        help_text="Type of product",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Product price",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original price for showing discounts",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Available stock (0 = unlimited for digital/trees)",
                    ),
                ),
                (
                    "is_unlimited_stock",
                    models.BooleanField(
                        default=False, help_text="If true, stock is not tracked"
                    ),
                ),
                (
                    "images",
                    models.JSONField(default=list, help_text="List of image URLs"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Average rating (0-5)",
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "reviews_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of reviews"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        help_text='List of feature strings (e.g., ["Organic", "Vegan"])',
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True,
                        help_text='Location name (e.g., "Sequoia National Forest")',
                        max_length=200,
                    ),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "co2_offset_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated CO2 offset in kg per year (for trees)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        blank=True, help_text="Tree species (for trees)", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether product is visible in catalog"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Whether to show in featured section"
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(
                        default=True, help_text='Whether to show "New" badge'
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta title (defaults to title if empty)",
                        max_length=70,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta description (defaults to short_description if empty)",
                        max_length=160,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Product category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="products_pr_slug_3edc0c_idx"),
                    models.Index(
                        fields=["category", "is_active"],
                        name="products_pr_categor_50f5f1_idx",
                    ),
                    models.Index(
                        fields=["product_type", "is_active"],
                        name="products_pr_product_a5a1ea_idx",
                    ),
                    models.Index(
                        fields=["is_featured", "is_active"],
                        name="products_pr_is_feat_a1ecf6_idx",
                    ),
                ],
            },
        ),
    ]
