# Generated by Django 5.2.9 on 2025-12-19 00:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
        migrations.AddField(
            model_name="product",
            name="area_size",
            field=models.CharField(
                blank=True,
                help_text='Tamaño del área (ej: "1 hectárea", "2,500 m²")',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="duration",
            field=models.CharField(
                blank=True,
                help_text='Duración de la experiencia (ej: "4 horas", "3 días")',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="impact_description",
            field=models.TextField(
                blank=True,
                help_text="Descripción del impacto que genera el apadrinamiento",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="includes",
            field=models.JSONField(
                default=list,
                help_text='Lista de lo que incluye (ej: ["Transporte", "Almuerzo"])',
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_collective",
            field=models.BooleanField(
                default=False,
                help_text="Si es apadrinamiento colectivo (varios padrinos)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="max_participants",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Máximo de participantes por experiencia",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pricing_type",
            field=models.CharField(
                choices=[("annual", "Suscripción Anual"), ("one_time", "Pago Único")],
                default="annual",
                help_text="Tipo de precio (anual o único)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="purpose",
            field=models.TextField(
                blank=True,
                help_text="Propósito del apadrinamiento - por qué es importante",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="compare_at_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio original para mostrar descuentos",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                default="USD", help_text="Código de moneda (ISO 4217)", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_unlimited_stock",
            field=models.BooleanField(
                default=True, help_text="Si es true, el stock no se rastrea"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Precio del producto",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("tree", "Árbol"),
                    ("forest", "Bosque"),
                    ("lagoon", "Laguna/Humedal"),
                    ("experience", "Experiencia"),
                ],
                help_text="Type of product",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Stock disponible (0 = ilimitado para apadrinamientos)",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Archivo de imagen",
                        null=True,
                        upload_to="products/%Y/%m/",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL externa de imagen (alternativa a subir archivo)",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Texto alternativo para accesibilidad",
                        max_length=200,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Descripción o pie de foto",
                        max_length=300,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Si es la imagen principal del producto",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de visualización"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto al que pertenece la imagen",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de Producto",
                "verbose_name_plural": "Imágenes de Productos",
                "ordering": ["display_order", "-is_primary"],
            },
        ),
        migrations.CreateModel(
            name="SponsorshipUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único (ej: TREE-001, LAG-GUATAVITA-001, FOREST-SN-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Nombre propio de la unidad (ej: "Roble del Amanecer", "Sector Norte Laguna")',
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL amigable", max_length=200, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("sponsored", "Apadrinado"),
                            ("reserved", "Reservado"),
                            ("inactive", "Inactivo"),
                        ],
                        default="available",
                        help_text="Estado actual de la unidad",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descripción específica de esta unidad"
                    ),
                ),
                (
                    "story",
                    models.TextField(
                        blank=True,
                        help_text="Historia o contexto especial de esta unidad",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True, help_text="Ubicación específica", max_length=200
                    ),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitud",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitud",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        blank=True, help_text="Especie (para árboles)", max_length=100
                    ),
                ),
                (
                    "age_years",
                    models.PositiveIntegerField(
                        blank=True, help_text="Edad en años", null=True
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveIntegerField(
                        blank=True, help_text="Altura actual en centímetros", null=True
                    ),
                ),
                (
                    "area_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Área en metros cuadrados",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "co2_absorbed_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="CO2 total absorbido hasta la fecha (kg)",
                        max_digits=10,
                    ),
                ),
                (
                    "co2_per_year",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="CO2 estimado por año (kg)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "sponsored_at",
                    models.DateTimeField(
                        blank=True, help_text="Fecha de apadrinamiento", null=True
                    ),
                ),
                (
                    "sponsorship_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de expiración del apadrinamiento",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Si está visible en el catálogo"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Si aparece en destacados"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Tipo de producto al que pertenece",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="products.product",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Padrino actual",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsored_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad de Apadrinamiento",
                "verbose_name_plural": "Unidades de Apadrinamiento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnitImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Archivo de imagen",
                        null=True,
                        upload_to="units/%Y/%m/",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, help_text="URL externa de imagen"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, help_text="Texto alternativo", max_length=200
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, help_text="Descripción de la foto", max_length=300
                    ),
                ),
                (
                    "taken_at",
                    models.DateField(
                        blank=True, help_text="Fecha en que se tomó la foto", null=True
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Si es la imagen principal"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de visualización"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unidad a la que pertenece",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="products.sponsorshipunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de Unidad",
                "verbose_name_plural": "Imágenes de Unidades",
                "ordering": ["display_order", "-is_primary"],
            },
        ),
        migrations.CreateModel(
            name="UnitUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("photo", "Nueva Foto"),
                            ("growth", "Crecimiento"),
                            ("milestone", "Hito Alcanzado"),
                            ("maintenance", "Mantenimiento"),
                            ("impact", "Reporte de Impacto"),
                            ("health", "Estado de Salud"),
                            ("weather", "Evento Climático"),
                            ("wildlife", "Avistamiento de Fauna"),
                        ],
                        default="photo",
                        help_text="Tipo de actualización",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título de la actualización", max_length=200
                    ),
                ),
                ("content", models.TextField(help_text="Contenido (soporta markdown)")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen de la actualización",
                        null=True,
                        upload_to="unit_updates/%Y/%m/",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, help_text="URL externa de imagen"),
                ),
                (
                    "height_cm",
                    models.PositiveIntegerField(
                        blank=True, help_text="Altura actual (cm)", null=True
                    ),
                ),
                (
                    "co2_absorbed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="CO2 absorbido acumulado (kg)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        blank=True,
                        help_text="Estado de salud (ej: Excelente, Bueno, Requiere atención)",
                        max_length=50,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Visible para todos o solo el padrino"
                    ),
                ),
                (
                    "notify_sponsor",
                    models.BooleanField(
                        default=True, help_text="Enviar notificación al padrino"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó la actualización",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unit_updates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unidad relacionada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="products.sponsorshipunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actualización de Unidad",
                "verbose_name_plural": "Actualizaciones de Unidades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("photo", "Nueva Foto"),
                            ("growth", "Crecimiento"),
                            ("milestone", "Hito Alcanzado"),
                            ("maintenance", "Mantenimiento"),
                            ("impact", "Reporte de Impacto"),
                            ("news", "Noticia"),
                            ("event", "Evento"),
                        ],
                        default="news",
                        help_text="Tipo de actualización",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título de la actualización", max_length=200
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Contenido de la actualización (soporta markdown)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen de la actualización",
                        null=True,
                        upload_to="updates/%Y/%m/",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, help_text="URL externa de imagen"),
                ),
                (
                    "co2_absorbed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="CO2 absorbido hasta la fecha (kg)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Altura actual en centímetros (para árboles)",
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Si es visible para todos o solo padrinos",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto relacionado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actualización de Producto",
                "verbose_name_plural": "Actualizaciones de Productos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"],
                        name="products_pr_product_549155_idx",
                    ),
                    models.Index(
                        fields=["update_type"], name="products_pr_update__2e3656_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sponsorshipunit",
            index=models.Index(fields=["code"], name="products_sp_code_ab914a_idx"),
        ),
        migrations.AddIndex(
            model_name="sponsorshipunit",
            index=models.Index(fields=["status"], name="products_sp_status_3524c3_idx"),
        ),
        migrations.AddIndex(
            model_name="sponsorshipunit",
            index=models.Index(
                fields=["product", "status"], name="products_sp_product_114538_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorshipunit",
            index=models.Index(
                fields=["sponsor"], name="products_sp_sponsor_1f7fff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unitupdate",
            index=models.Index(
                fields=["unit", "-created_at"], name="products_un_unit_id_006d41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unitupdate",
            index=models.Index(
                fields=["update_type"], name="products_un_update__a98ede_idx"
            ),
        ),
    ]
