# Generated by Django 5.2.9 on 2025-12-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_images_product_area_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorshipunit",
            name="location_area",
            field=models.CharField(
                blank=True,
                help_text='Área general (ej: "Sierra Nevada, Colombia")',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sponsorshipunit",
            name="location_lat_approx",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Latitud aproximada (3 decimales = ~100m de precisión)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sponsorshipunit",
            name="location_lng_approx",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Longitud aproximada (3 decimales = ~100m de precisión)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sponsorshipunit",
            name="location_radius_km",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Radio del área aproximada en km (para mostrar círculo en mapa)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipunit",
            name="location_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitud exacta (solo padrinos)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipunit",
            name="location_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitud exacta (solo padrinos)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipunit",
            name="location_name",
            field=models.CharField(
                blank=True,
                help_text="Ubicación específica (visible para padrinos)",
                max_length=200,
            ),
        ),
    ]
