# Generated by Django 5.2.9 on 2025-12-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_sponsorshipunit_location_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorshipunit",
            name="location_radius_km",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="Radio del área aproximada en km (para mostrar círculo en mapa)",
                max_digits=5,
            ),
        ),
    ]
