# Generated by Django 5.2.9 on 2025-12-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_sponsorshipunit_location_radius_km"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(
                blank=True, help_text="Category description in English"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                blank=True, help_text="Category name in English", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(
                blank=True, help_text="Full product description in English"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="impact_description_en",
            field=models.TextField(
                blank=True, help_text="Impact description in English"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="purpose_en",
            field=models.TextField(blank=True, help_text="Purpose in English"),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description_en",
            field=models.CharField(
                blank=True, help_text="Brief description in English", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="title_en",
            field=models.CharField(
                blank=True, help_text="Product title in English", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="Category description - Default/Spanish"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text='Category name (e.g., "Trees", "Retreats") - Default/Spanish',
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                help_text="Full product description (supports markdown) - Default/Spanish"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="impact_description",
            field=models.TextField(
                blank=True, help_text="Descripción del impacto - Default/Spanish"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="purpose",
            field=models.TextField(
                blank=True, help_text="Propósito del apadrinamiento - Default/Spanish"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                help_text="Brief description for cards and SEO meta - Default/Spanish",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                help_text="Product title - Default/Spanish", max_length=200
            ),
        ),
    ]
