# Generated by Django 5.2.9 on 2025-12-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_add_translation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="duration_en",
            field=models.CharField(
                blank=True,
                help_text='Duration in English (e.g., "4 hours", "3 days")',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="features_en",
            field=models.JSONField(
                default=list,
                help_text='Features in English (e.g., ["Organic", "Vegan"])',
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="includes_en",
            field=models.JSONField(
                default=list,
                help_text='What is included in English (e.g., ["Transport", "Lunch"])',
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="duration",
            field=models.CharField(
                blank=True,
                help_text="Duración de la experiencia - Default/Spanish",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="features",
            field=models.JSONField(
                default=list, help_text="List of features - Default/Spanish"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="includes",
            field=models.JSONField(
                default=list, help_text="Lista de lo que incluye - Default/Spanish"
            ),
        ),
    ]
