# Generated by Django 6.0 on 2025-12-18 21:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdoptedTree",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique tree identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tree_number",
                    models.CharField(
                        editable=False,
                        help_text='Human-readable tree number (e.g., "SEQ-2024-0001")',
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        help_text="User-given nickname for the tree",
                        max_length=100,
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        help_text="Tree species (copied from product)", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Healthy", "Healthy"),
                            ("Maintenance", "Under Maintenance"),
                            ("Critical", "Critical"),
                            ("Dormant", "Dormant (Winter)"),
                        ],
                        default="Healthy",
                        help_text="Current health status of the tree",
                        max_length=20,
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        help_text='Location name (e.g., "Sequoia National Forest")',
                        max_length=200,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="GPS latitude coordinate",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="GPS longitude coordinate",
                        max_digits=9,
                    ),
                ),
                (
                    "age_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Age of the tree in days since planting"
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current height in centimeters",
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "co2_offset_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total CO2 offset in kilograms",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "certificate_url",
                    models.URLField(
                        blank=True, help_text="URL to downloadable adoption certificate"
                    ),
                ),
                (
                    "adoption_date",
                    models.DateField(help_text="Date when the tree was adopted"),
                ),
                (
                    "planted_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the tree was physically planted",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_item",
                    models.OneToOneField(
                        blank=True,
                        help_text="The order item that created this adoption",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adopted_tree",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The tree product that was purchased",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adoptions",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who adopted this tree",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adopted_trees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Adopted Tree",
                "verbose_name_plural": "Adopted Trees",
                "ordering": ["-adoption_date"],
            },
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Milestone", "Milestone"),
                            ("Audit", "Audit"),
                            ("Update", "Update"),
                            ("Maintenance", "Maintenance"),
                            ("Photo", "Photo Update"),
                        ],
                        help_text="Type of timeline event",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Event title", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the event"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="eco",
                        help_text="Material Symbol icon name",
                        max_length=50,
                    ),
                ),
                (
                    "event_date",
                    models.DateField(help_text="Date when the event occurred"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tree",
                    models.ForeignKey(
                        help_text="The tree this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="ecosystems.adoptedtree",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timeline Event",
                "verbose_name_plural": "Timeline Events",
                "ordering": ["-event_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TreeGalleryImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.URLField(help_text="URL to the image")),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, help_text="URL to thumbnail version"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, help_text="Image caption", max_length=300
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for accessibility",
                        max_length=200,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary/featured image",
                    ),
                ),
                (
                    "taken_date",
                    models.DateField(
                        blank=True, help_text="Date when the photo was taken", null=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tree",
                    models.ForeignKey(
                        help_text="The tree this image belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="ecosystems.adoptedtree",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tree Gallery Image",
                "verbose_name_plural": "Tree Gallery Images",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="adoptedtree",
            index=models.Index(
                fields=["tree_number"], name="ecosystems__tree_nu_1ef2a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adoptedtree",
            index=models.Index(
                fields=["user", "status"], name="ecosystems__user_id_82a826_idx"
            ),
        ),
    ]
