# Generated by Django 6.0 on 2025-12-18 21:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Badge name", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of how to earn this badge"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Material Symbol icon name", max_length=50
                    ),
                ),
                (
                    "points_value",
                    models.PositiveIntegerField(
                        default=0, help_text="Points awarded when badge is earned"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name shown in the UI",
                        max_length=100,
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(blank=True, help_text="URL to user profile photo"),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("dark", "Dark"),
                            ("light", "Light"),
                            ("system", "System"),
                        ],
                        default="dark",
                        help_text="UI theme preference",
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "US Dollar"), ("EUR", "Euro")],
                        default="USD",
                        help_text="Preferred currency for prices",
                        max_length=3,
                    ),
                ),
                (
                    "notify_email",
                    models.BooleanField(
                        default=True, help_text="Receive email notifications"
                    ),
                ),
                (
                    "notify_push",
                    models.BooleanField(
                        default=True, help_text="Receive push notifications"
                    ),
                ),
                (
                    "notify_tree_updates",
                    models.BooleanField(
                        default=True, help_text="Receive updates about adopted trees"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Seed", "Seed"),
                            ("Sprout", "Sprout"),
                            ("Sapling", "Sapling"),
                            ("Earth Guardian", "Earth Guardian"),
                            ("Forest Master", "Forest Master"),
                        ],
                        default="Seed",
                        help_text="Current gamification level",
                        max_length=20,
                    ),
                ),
                (
                    "current_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current green points balance",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_points_earned",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total points earned all time",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The Django user this profile belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "awarded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the badge was awarded"
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        help_text="The badge that was earned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awarded_to",
                        to="users.badge",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        help_text="The user who earned this badge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Badge",
                "verbose_name_plural": "User Badges",
                "ordering": ["-awarded_at"],
                "unique_together": {("user_profile", "badge")},
            },
        ),
    ]
