# Generated by Django 5.2.9 on 2025-12-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="User profile photo",
                null=True,
                upload_to="users/avatars/",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="photo_url",
            field=models.URLField(
                blank=True, help_text="URL to user profile photo (external)"
            ),
        ),
    ]
